backend:
  name: git-gateway

# when using the default proxy server port
local_backend: true

media_folder: static/assets
public_folder: /assets
collections:
  - name: project
    label: Projects
    folder: content/projects
    create: true
    fields:
      - { name: templateKey, label: Template Key, required: true, widget: hidden, default: project }
      - { name: slug, label: Slug, widget: string }
      - { name: year, label: Year, widget: date, format: YYYY, date_format: YYYY }
      - { name: company, label: Company }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }
      - { name: thumbnail, label: Thumbnail, widget: image, allow_multiple: false}
  - name: paragraphs
    label: Paragraphs
    folder: content/paragraphs
    create: true
    fields:
      - { name: templateKey, label: Template Key, required: true, widget: hidden, default: paragraph }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
  - name: workExperiences
    label: Work experiences
    folder: content/workExperiences
    create: true
    fields:
      - { name: templateKey, label: Template Key, required: true, widget: hidden, default: workExperience }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: text }
      - { name: startingDate, label: Starting Date, widget: date, format: MM YYYY, date_format: MM YYYY }
      - { name: endingDate, label: Ending Date, widget: date, format: MM YYYY, date_format: MM YYYY }